name: test-deploy
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: install dependencies
      run: npm ci
    - name: run scripts
      run: |
        npm run test && npm run lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      my-output: ${{ steps.output-1.outputs.this-output}} 
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: install dependencies
      run: npm ci
    - name: build
      run: npm run build
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-files     # this gives a zip file
        path: |
          dist
          package.json
    - name: downlod artifact
      uses: actions/download-artifact@v4
      with:
        name: dist-files
    - name: output artifact
      run: ls
    - name: publish js file name
      id: output-1
      run: find dist/assets/*.js -type f -exec echo 'this-output={}' >> $GITHUB_OUTPUT ';'